project_id: '640226'
options commit_message: Update Translation from Crowdin Platform
pull_request_title: '[Crowdin] Update Localization Files'
files:
  - source: /JapaneseCallouts/Resources/ja-JP.json
    translation: /JapaneseCallouts/Resources/%locale%.json
