options commit_message: Update Translation from Crowdin Platform
pull_request_title: '[Crowdin] Update Localization Files'
files:
  - source: /JapaneseCallouts/Localization/en-US.json
    translation: /JapaneseCallouts/Localization/%locale%.json
