//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JapaneseCallouts.Localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BankHeistConversation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BankHeistConversation() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JapaneseCallouts.Localization.BankHeistConversation", typeof(BankHeistConversation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Well, do you want to kill the alarm? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alarm1 {
            get {
                return ResourceManager.GetString("Alarm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tech team... it&apos;s me... yes... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alarm2 {
            get {
                return ResourceManager.GetString("Alarm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   That&apos;s all. If you want to turn on again, please radio to tech team. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alarm3 {
            get {
                return ResourceManager.GetString("Alarm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You sure? If you want to turn off, please radio to tech team. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alarm4 {
            get {
                return ResourceManager.GetString("Alarm4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Good luck, officer! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alarm5 {
            get {
                return ResourceManager.GetString("Alarm5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes, I want to kill the alarm. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlarmSelection1 {
            get {
                return ResourceManager.GetString("AlarmSelection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No, it&apos;s not necessary. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlarmSelection2 {
            get {
                return ResourceManager.GetString("AlarmSelection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Also worried about the hostages. ~y~Let&apos;s try to discuss with them~s~. How can I talk with them? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Discuss1 {
            get {
                return ResourceManager.GetString("Discuss1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The technology team got ~b~robbers phone number~s~. Maybe we can use it. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Discuss2 {
            get {
                return ResourceManager.GetString("Discuss2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK, I&apos;ll try it. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Discuss3 {
            get {
                return ResourceManager.GetString("Discuss3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~y~Let&apos;s fight to help all hostages and end this incident quickly.~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fight1 {
            get {
                return ResourceManager.GetString("Fight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Good. Don&apos;t worry. The SWAT units are already stand by. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fight2 {
            get {
                return ResourceManager.GetString("Fight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~b~There are some gear in the back of the riot vans.~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fight3 {
            get {
                return ResourceManager.GetString("Fight3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All rights, sir. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fight4 {
            get {
                return ResourceManager.GetString("Fight4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~g~Thank you for your all of work!~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Final1 {
            get {
                return ResourceManager.GetString("Final1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I will send you the operation report soon. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Final2 {
            get {
                return ResourceManager.GetString("Final2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Good work today officer, ~g~thank you~s~. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Final3 {
            get {
                return ResourceManager.GetString("Final3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Just doing my job, sir. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Final4 {
            get {
                return ResourceManager.GetString("Final4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks very bad, what&apos;s the situation? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro1 {
            get {
                return ResourceManager.GetString("Intro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~r~There are many robbers in the bank~s~, but we don&apos;t know how many they are. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro2 {
            get {
                return ResourceManager.GetString("Intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Well, are there any hostages? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro3 {
            get {
                return ResourceManager.GetString("Intro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeah, they have ~y~8 hostages~s~ in the bank... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro4 {
            get {
                return ResourceManager.GetString("Intro4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We have two ways to solve this incident. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro5 {
            get {
                return ResourceManager.GetString("Intro5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First one is ~y~discussing with them~s~. They may stop this wrong activity. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro6 {
            get {
                return ResourceManager.GetString("Intro6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Second one is ~y~fighting with them~s~. We have SWAT units and ready. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro7 {
            get {
                return ResourceManager.GetString("Intro7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Which do you choose? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro8 {
            get {
                return ResourceManager.GetString("Intro8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try to discuss with them. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IntroSelection1 {
            get {
                return ResourceManager.GetString("IntroSelection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fight to help all hostages. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IntroSelection2 {
            get {
                return ResourceManager.GetString("IntroSelection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~g~Green light!~s~ Move in! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MoveIn {
            get {
                return ResourceManager.GetString("MoveIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Look, there are ~b~many officers~s~ around the bank. We want to end this incident ~g~peacefully~s~. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation11 {
            get {
                return ResourceManager.GetString("Negotiation11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~b~Calm down~s~. We just want nobody to get hurt. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation111 {
            get {
                return ResourceManager.GetString("Negotiation111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can you say the same thing to your wife, ~b~{0}~s~ that you said to me? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation1111 {
            get {
                return ResourceManager.GetString("Negotiation1111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Why do you know my wife!? ~r~Leave my family immediately!~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation1112 {
            get {
                return ResourceManager.GetString("Negotiation1112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~r~Don&apos;t tell me anymore! You can&apos;t stop us!~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation112 {
            get {
                return ResourceManager.GetString("Negotiation112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I&apos;m sorry, but your action is ~r~wrong~s~. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation1121 {
            get {
                return ResourceManager.GetString("Negotiation1121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You don&apos;t have to say sorry. I understand what you want to do. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation1122 {
            get {
                return ResourceManager.GetString("Negotiation1122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   But it&apos;s our problem. Bye, officer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation1123 {
            get {
                return ResourceManager.GetString("Negotiation1123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are trying to save your family, but ~y~could the money you got make your family happy?~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation1131 {
            get {
                return ResourceManager.GetString("Negotiation1131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation1132 {
            get {
                return ResourceManager.GetString("Negotiation1132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~y~Officer, what I should do? I can&apos;t think anymore... Why did I do...~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation1133 {
            get {
                return ResourceManager.GetString("Negotiation1133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You only have to get out of the bank with your member. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation1134 {
            get {
                return ResourceManager.GetString("Negotiation1134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alright, officer. ~g~Thanks for making me think again.~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation1135 {
            get {
                return ResourceManager.GetString("Negotiation1135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~r~Fuck you!~s~ Do you want to ~r~kill the hostages!?~s~ Or what? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation12 {
            get {
                return ResourceManager.GetString("Negotiation12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will do that and all the cops in this city will come here! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation131 {
            get {
                return ResourceManager.GetString("Negotiation131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t say things like that, or you might get a fight with a ~b~SWAT teams~s~. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation1311 {
            get {
                return ResourceManager.GetString("Negotiation1311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~r~Fuck you pig!~s~ You and everyone else are going to ~r~die~s~! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation1312 {
            get {
                return ResourceManager.GetString("Negotiation1312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~r~And all hostages will be dead!~s~ Haha! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation132 {
            get {
                return ResourceManager.GetString("Negotiation132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~b~Don&apos;t you want to meet again your family?~s~ The hostages are probably thinking the same thing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation1331 {
            get {
                return ResourceManager.GetString("Negotiation1331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Of course I do... OK, we are coming out. ~y~Don&apos;t shoot please!~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation1332 {
            get {
                return ResourceManager.GetString("Negotiation1332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Well, what kind of deal do you give me? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation31 {
            get {
                return ResourceManager.GetString("Negotiation31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We are not going to end things ~g~peacefully~s~. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation311 {
            get {
                return ResourceManager.GetString("Negotiation311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We&apos;re interested in a free plane ticket to ~b~Liberty City~s~, first class! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation321 {
            get {
                return ResourceManager.GetString("Negotiation321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You know that won&apos;t get approved right? ~b~Don&apos;t you want to see your family again?~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation3211 {
            get {
                return ResourceManager.GetString("Negotiation3211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Of course I do. Alright, we are coming out, ~y~don&apos;t shoot!~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation3212 {
            get {
                return ResourceManager.GetString("Negotiation3212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are stupid? I said we need the airplane! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation3221 {
            get {
                return ResourceManager.GetString("Negotiation3221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Officer, I&apos;ll tell you a good thing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation3231 {
            get {
                return ResourceManager.GetString("Negotiation3231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~r~There is a lot of money in the bank!~s~ Hehe! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation3232 {
            get {
                return ResourceManager.GetString("Negotiation3232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I have no idea, but I&apos;m sure we can still make a deal. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation331 {
            get {
                return ResourceManager.GetString("Negotiation331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You should better to start making any good deals soon then. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation332 {
            get {
                return ResourceManager.GetString("Negotiation332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   But you don&apos;t have any idea, right? ~r~So you can&apos;t deal!~s~ lol に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negotiation333 {
            get {
                return ResourceManager.GetString("Negotiation333", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are many officers. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection1 {
            get {
                return ResourceManager.GetString("NegotiationSelection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t you want to meet again your family? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection10 {
            get {
                return ResourceManager.GetString("NegotiationSelection10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What are you interested in? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection11 {
            get {
                return ResourceManager.GetString("NegotiationSelection11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No idea. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection12 {
            get {
                return ResourceManager.GetString("NegotiationSelection12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t you want to see your family again? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection13 {
            get {
                return ResourceManager.GetString("NegotiationSelection13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Release the hostage first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection14 {
            get {
                return ResourceManager.GetString("NegotiationSelection14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Give you a briefcase filled the money. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection15 {
            get {
                return ResourceManager.GetString("NegotiationSelection15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What do you want? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection2 {
            get {
                return ResourceManager.GetString("NegotiationSelection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t we make a deal? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection3 {
            get {
                return ResourceManager.GetString("NegotiationSelection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calm down. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection4 {
            get {
                return ResourceManager.GetString("NegotiationSelection4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All the cops in this city will come here! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection5 {
            get {
                return ResourceManager.GetString("NegotiationSelection5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can you say the same thing to your wife? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection6 {
            get {
                return ResourceManager.GetString("NegotiationSelection6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I&apos;m sorry. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection7 {
            get {
                return ResourceManager.GetString("NegotiationSelection7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are trying to save your familly, but... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection8 {
            get {
                return ResourceManager.GetString("NegotiationSelection8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t say things like that. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NegotiationSelection9 {
            get {
                return ResourceManager.GetString("NegotiationSelection9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What&apos;s up!? I&apos;m ~r~busy~s~ now! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I am the officer, who am I speaking to? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~r~Shut up!~s~ No time to speak with you! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Phone3 {
            get {
                return ResourceManager.GetString("Phone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We want a bus to take us to ~b~International Airport~s~. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request1 {
            get {
                return ResourceManager.GetString("Request1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What do you mean? ~y~The bus won&apos;t come?~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request11 {
            get {
                return ResourceManager.GetString("Request11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please wait. It needs time to come to the bus here... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request12 {
            get {
                return ResourceManager.GetString("Request12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~r~I can&apos;t believe what you said.~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request13 {
            get {
                return ResourceManager.GetString("Request13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From there, we want a plane to fly us to ~b~Liberty City~s~. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request2 {
            get {
                return ResourceManager.GetString("Request2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~r~Fuck you!~s~ You will come in after there are no hostages, won&apos;t you!? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request21 {
            get {
                return ResourceManager.GetString("Request21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~y~The bus won&apos;t come if you don&apos;t release hostages~s~. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request211 {
            get {
                return ResourceManager.GetString("Request211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OKOK... Your brain is ~r~fucking shit!~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request212 {
            get {
                return ResourceManager.GetString("Request212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   They come out when I see the bus! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request22 {
            get {
                return ResourceManager.GetString("Request22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thank you too. ~y~Don&apos;t shoot my husband!~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request220 {
            get {
                return ResourceManager.GetString("Request220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I have your wife, ~b~{0}~s~. ~g~She wants to talk with you.~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request221 {
            get {
                return ResourceManager.GetString("Request221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let me talk to her. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request222 {
            get {
                return ResourceManager.GetString("Request222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wait for a moment, she is coming. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request223 {
            get {
                return ResourceManager.GetString("Request223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~q~Baby! Please come out! Think again about our kids!~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request224 {
            get {
                return ResourceManager.GetString("Request224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~q~Please! Stop doing such a thing!~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request225 {
            get {
                return ResourceManager.GetString("Request225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I&apos;m sorry ~b~{0}~s~... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request226 {
            get {
                return ResourceManager.GetString("Request226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I really don&apos;t know why I&apos;m here... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request227 {
            get {
                return ResourceManager.GetString("Request227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I love you ~b~{0}~s~! ~g~I&apos;m coming out!~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request228 {
            get {
                return ResourceManager.GetString("Request228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thank you, Mrs.~b~{0}~s~. For safety, please get back into a police car. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request229 {
            get {
                return ResourceManager.GetString("Request229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~y~Release the hostages, now!~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request231 {
            get {
                return ResourceManager.GetString("Request231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I won&apos;t release hostages that easily. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request31 {
            get {
                return ResourceManager.GetString("Request31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This action is necessary to help my family. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request32 {
            get {
                return ResourceManager.GetString("Request32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~r~But you won&apos;t understand forever.~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Request33 {
            get {
                return ResourceManager.GetString("Request33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I&apos;ll try to work on it but I can&apos;t guarantee anything. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequestSelection1 {
            get {
                return ResourceManager.GetString("RequestSelection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK, we have a bus on the way, but you need to release the hostages first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequestSelection2 {
            get {
                return ResourceManager.GetString("RequestSelection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Release hostage now and I&apos;ll cut your sentences by 5 years. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequestSelection3 {
            get {
                return ResourceManager.GetString("RequestSelection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The bus won&apos;t come here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequestSelection4 {
            get {
                return ResourceManager.GetString("RequestSelection4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I have your wife. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequestSelection5 {
            get {
                return ResourceManager.GetString("RequestSelection5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Release the hostages! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequestSelection6 {
            get {
                return ResourceManager.GetString("RequestSelection6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Come on! ~g~It&apos;s safe~s~, get to the ambulance outside! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RescueHostage {
            get {
                return ResourceManager.GetString("RescueHostage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The ~r~robbers~s~ seem to be surrendering. Get in position behind a ~b~police car~s~. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeemSurrender {
            get {
                return ResourceManager.GetString("SeemSurrender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go on! ~y~There are still hostages in there!~s~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StillFighting {
            get {
                return ResourceManager.GetString("StillFighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~g~Amaizing job~s~, officer! It seems the robbers were ~g~surrendered~s~! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Surrender1 {
            get {
                return ResourceManager.GetString("Surrender1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your job now is ~b~rescue all hostages from the bank~s~. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Surrender2 {
            get {
                return ResourceManager.GetString("Surrender2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please take care, ~y~you never know what the robbers left inside~s~. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Surrender3 {
            get {
                return ResourceManager.GetString("Surrender3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We have no idea if there are still robbers inside. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Surrender4 {
            get {
                return ResourceManager.GetString("Surrender4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All rights, sir. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Surrender5 {
            get {
                return ResourceManager.GetString("Surrender5", resourceCulture);
            }
        }
    }
}
