//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JapaneseCallouts.Localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BankHeistConversation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BankHeistConversation() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JapaneseCallouts.Localization.BankHeistConversation", typeof(BankHeistConversation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks very bad, what&apos;s the situation? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro1 {
            get {
                return ResourceManager.GetString("Intro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are many robbers in the bank, we can&apos;t how many are they. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro2 {
            get {
                return ResourceManager.GetString("Intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Well, are there any hostages? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro3 {
            get {
                return ResourceManager.GetString("Intro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeah, they have 8 hostages in the bank... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro4 {
            get {
                return ResourceManager.GetString("Intro4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We have two ways to solve this incident. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro5 {
            get {
                return ResourceManager.GetString("Intro5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First one is discussing with them. They may stop this wrong activity. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro6 {
            get {
                return ResourceManager.GetString("Intro6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Second one is fighting with them. We have SWAT units and ready. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro7 {
            get {
                return ResourceManager.GetString("Intro7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Which do you choose? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro8 {
            get {
                return ResourceManager.GetString("Intro8", resourceCulture);
            }
        }
    }
}
