//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JapaneseCallouts.Localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoadRageConversation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoadRageConversation() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JapaneseCallouts.Localization.RoadRageConversation", typeof(RoadRageConversation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Thank you, officer. The road rage was very scary. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Final1 {
            get {
                return ResourceManager.GetString("Final1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No problem, sir. So, why did you get the suspect angry? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Final2 {
            get {
                return ResourceManager.GetString("Final2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I don&apos;t know, officer. I was driving normally as on other days. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Final3 {
            get {
                return ResourceManager.GetString("Final3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you come to the police station a few days later to tell us what happened? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Final4 {
            get {
                return ResourceManager.GetString("Final4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sure. Have a good day, officer! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Final5 {
            get {
                return ResourceManager.GetString("Final5", resourceCulture);
            }
        }
    }
}
